### ISSUE TITLE
Can't compile using OpenCV 4.0.1

### ISSUE THREAD

**Issue by TimBluesWin** [samyak-268/facial-feature-detection#7]
I tried to compile your program using OpenCV 4.0.1, and Operating System Trisquel 8.0 Flidas, but the following error occurs:

roi/libEYEBROW_ROI.a(eyebrow_roi.cpp.o): In function `EyebrowROI::detectFace()':
eyebrow_roi.cpp:(.text+0x44a): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::Mat const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
roi/libEYEBROW_ROI.a(eyebrow_roi.cpp.o): In function `EyebrowROI::detectEyebrows()':
eyebrow_roi.cpp:(.text+0x602): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::Mat const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
roi/libEYEBROW_ROI.a(eyebrow_roi.cpp.o): In function `cv::Ptr<CvHaarClassifierCascade>::release()':
eyebrow_roi.cpp:(.text._ZN2cv3PtrI23CvHaarClassifierCascadeE7releaseEv[_ZN2cv3PtrI23CvHaarClassifierCascadeE7releaseEv]+0x47): undefined reference to `cv::Ptr<CvHaarClassifierCascade>::delete_obj()'

Any help would be appreciated. Thanks.
